# Generated by Django 3.1.7 on 2023-12-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inmakes_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('comment', models.TextField()),
                ('cus_image', models.ImageField(upload_to='customer_img')),
            ],
        ),
    ]
